version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "cargo"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "01:00"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      cargo:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
